In [87]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt

In [88]:
from sklearn.model_selection import train_test_split

from sklearn.compose import ColumnTransformer

from sklearn.metrics import accuracy_score

from sklearn.tree import DecisionTreeClassifier

In [91]:
df = pd.read_csv('train.csv',usecols=['Age','Fare','SibSp','Parch','Survived'])

In [92]:
df.head()

   Survived   Age  SibSp  Parch     Fare
0         0  22.0      1      0   7.2500
1         1  38.0      1      0  71.2833
2         1  26.0      0      0   7.9250
3         1  35.0      1      0  53.1000
4         0  35.0      0      0   8.0500

In [93]:
df.dropna(inplace=True)

In [94]:
df['Family'] = df['SibSp']+df['Parch']

In [95]:
df.head()

   Survived   Age  SibSp  Parch     Fare  Family
0         0  22.0      1      0   7.2500       1
1         1  38.0      1      0  71.2833       1
2         1  26.0      0      0   7.9250       0
3         1  35.0      1      0  53.1000       1
4         0  35.0      0      0   8.0500       0

In [96]:
df.drop(columns=['SibSp','Parch'],inplace=True)

In [97]:
df.head()

   Survived   Age     Fare  Family
0         0  22.0   7.2500       1
1         1  38.0  71.2833       1
2         1  26.0   7.9250       0
3         1  35.0  53.1000       1
4         0  35.0   8.0500       0

In [98]:
X = df.drop(columns=['Survived'])
Y = df['Survived']

In [99]:
x_train,x_test,y_train,y_test = train_test_split(X,Y,test_size=0.2,random_state=42)

In [100]:
x_train.head()

      Age     Fare  Family
328  31.0  20.5250       2
73   26.0  14.4542       1
253  30.0  16.1000       1
719  33.0   7.7750       0
666  25.0  13.0000       0

## Without Binarization

In [103]:
clf=DecisionTreeClassifier()

clf.fit(x_train,y_train)

y_pred=clf.predict(x_test)

accuracy_score(y_pred,y_test)

0.6223776223776224

In [104]:
np.mean(cross_val_score(DecisionTreeClassifier(),X,Y,cv=10,scoring="accuracy"))

np.float64(0.6373043818466353)

## Applying Binarization

In [105]:
from sklearn.preprocessing import Binarizer

In [108]:
trf=ColumnTransformer([
    ("bin",Binarizer(copy=False),["Family"])
],remainder="passthrough")

# We want changes in existing column that's why we kept 'copy = False' in the above function

In [109]:
X_train_trf=trf.fit_transform(x_train)
X_test_trf=trf.transform(x_test)

In [110]:
pd.DataFrame(X_train_trf,columns=["Family","Age","Fare"])

     Family   Age      Fare
0       1.0  31.0   20.5250
1       1.0  26.0   14.4542
2       1.0  30.0   16.1000
3       0.0  33.0    7.7750
4       0.0  25.0   13.0000
..      ...   ...       ...
566     1.0  46.0   61.1750
567     0.0  25.0   13.0000
568     0.0  41.0  134.5000
569     1.0  33.0   20.5250
570     0.0  33.0    7.8958

[571 rows x 3 columns]

In [111]:
clf1=DecisionTreeClassifier()

clf1.fit(X_train_trf,y_train)

Y_pred2=clf1.predict(X_test_trf)

accuracy_score(Y_pred2,y_test)

0.6153846153846154

In [112]:
X_trf=trf.transform(X)

np.mean(cross_val_score(DecisionTreeClassifier(),X_trf,Y,cv=10,scoring="accuracy"))

np.float64(0.6275821596244132)