In [1]:
import pandas as pd
import numpy as np

In [2]:
date = pd.read_csv('orders.csv')
time = pd.read_csv('messages.csv')

In [3]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [4]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [5]:
date.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   str
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), str(1)
memory usage: 31.4 KB

In [6]:
time.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   str
 1   msg     1000 non-null   str
dtypes: str(2)
memory usage: 15.8 KB

## Working with Dates

In [7]:
# Converting to DATE-TIME datatype

date['date'] = pd.to_datetime(date['date'])

In [8]:
date.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[us]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[us](1), int64(3)
memory usage: 31.4 KB

#### 1. Extracting year

In [32]:
date['date_year'] = date['date'].dt.year

In [33]:
date.head()

,date,product_id,city_id,orders,date_year,date_month,date_month_name,date_day,date_day_of_week
0,2019-12-10,5628,25,3,2019,1,December,10,1
1,2018-08-15,3646,14,157,2018,2,August,15,2
2,2018-10-23,1859,25,1,2018,1,October,23,1
3,2019-08-17,7292,25,1,2019,5,August,17,5
4,2019-01-06,4344,25,3,2019,6,January,6,6

#### 2. Extracting Month

In [34]:
date['date_month'] = date['date'].dt.month

In [35]:
date.sample(5)

,date,product_id,city_id,orders,date_year,date_month,date_month_name,date_day,date_day_of_week
810,2019-06-25,1187,2,45,2019,6,June,25,1
499,2018-09-28,1225,13,40,2018,9,September,28,4
385,2018-07-24,4306,14,11,2018,7,July,24,1
607,2019-05-27,3685,0,1,2019,5,May,27,0
689,2019-06-18,4530,26,108,2019,6,June,18,1

In [36]:
date['date_month_name'] = date['date'].dt.month_name()

In [37]:
date.sample(5)

,date,product_id,city_id,orders,date_year,date_month,date_month_name,date_day,date_day_of_week
46,2018-09-23,2815,13,1,2018,9,September,23,6
512,2019-12-12,4968,28,2,2019,12,December,12,3
681,2018-09-08,6483,28,2,2018,9,September,8,5
196,2018-08-20,6215,22,4,2018,8,August,20,0
12,2019-03-15,5665,5,1,2019,3,March,15,4

#### 3. Extracting days

In [38]:
date['date_day'] = date['date'].dt.day

In [39]:
date.sample(5)

,date,product_id,city_id,orders,date_year,date_month,date_month_name,date_day,date_day_of_week
584,2018-12-16,1520,26,168,2018,12,December,16,6
176,2018-12-16,1475,16,8,2018,12,December,16,6
100,2018-11-22,6343,22,191,2018,11,November,22,3
837,2018-12-15,5407,13,68,2018,12,December,15,5
309,2019-08-14,4352,16,1,2019,8,August,14,2

In [40]:
# Day of the week

date['date_day_of_week'] = date['date'].dt.dayofweek

In [41]:
date.sample(5)

,date,product_id,city_id,orders,date_year,date_month,date_month_name,date_day,date_day_of_week
421,2019-07-05,5970,26,1,2019,7,July,5,4
360,2019-03-23,435,7,2,2019,3,March,23,5
214,2019-06-30,453,16,2,2019,6,June,30,6
692,2019-02-18,7419,16,1,2019,2,February,18,0
448,2018-12-07,1933,21,17,2018,12,December,7,4

In [42]:
date['date_day_name'] = date['date'].dt.day_name()
date.sample(5)

,date,product_id,city_id,orders,date_year,date_month,date_month_name,date_day,date_day_of_week,date_day_name
117,2019-05-20,1556,17,2,2019,5,May,20,0,Monday
898,2019-02-20,2945,22,2,2019,2,February,20,2,Wednesday
394,2018-12-16,7034,13,1,2018,12,December,16,6,Sunday
512,2019-12-12,4968,28,2,2019,12,December,12,3,Thursday
374,2018-12-16,4595,13,1,2018,12,December,16,6,Sunday

In [44]:
# is it weekend..?
date['date_is_weekend'] = np.where(date['date_day_name'].isin(['Sunday', 'Saturday']), 1,0)

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month,date_month_name,date_day,date_day_of_week,date_day_name,date_is_weekend
0,2019-12-10,2019,12,December,10,1,Tuesday,0
1,2018-08-15,2018,8,August,15,2,Wednesday,0
2,2018-10-23,2018,10,October,23,1,Tuesday,0
3,2019-08-17,2019,8,August,17,5,Saturday,1
4,2019-01-06,2019,1,January,6,6,Sunday,1

#### 4. Extract Week of the year

In [48]:
date['date_week'] = date['date'].dt.weekday

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month,date_month_name,date_day,date_day_of_week,date_day_name,date_is_weekend,date_quarter,date_week
0,2019-12-10,2019,12,December,10,1,Tuesday,0,4,1
1,2018-08-15,2018,8,August,15,2,Wednesday,0,3,2
2,2018-10-23,2018,10,October,23,1,Tuesday,0,4,1
3,2019-08-17,2019,8,August,17,5,Saturday,1,3,5
4,2019-01-06,2019,1,January,6,6,Sunday,1,1,6

### 5. Extract Quarter

In [49]:
date["date_quarter"] = date["date"].dt.quarter
date.drop(columns=["product_id","orders","city_id"]).head()

,date,date_year,date_month,date_month_name,date_day,date_day_of_week,date_day_name,date_is_weekend,date_quarter,date_week
0,2019-12-10,2019,12,December,10,1,Tuesday,0,4,1
1,2018-08-15,2018,8,August,15,2,Wednesday,0,3,2
2,2018-10-23,2018,10,October,23,1,Tuesday,0,4,1
3,2019-08-17,2019,8,August,17,5,Saturday,1,3,5
4,2019-01-06,2019,1,January,6,6,Sunday,1,1,6

#### 6. Extract Semester

In [50]:
date["semester"] = np.where(date["date_quarter"].isin([1,2]),1,2)

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month,date_month_name,date_day,date_day_of_week,date_day_name,date_is_weekend,date_quarter,date_week,semester
0,2019-12-10,2019,12,December,10,1,Tuesday,0,4,1,2
1,2018-08-15,2018,8,August,15,2,Wednesday,0,3,2,2
2,2018-10-23,2018,10,October,23,1,Tuesday,0,4,1,2
3,2019-08-17,2019,8,August,17,5,Saturday,1,3,5,2
4,2019-01-06,2019,1,January,6,6,Sunday,1,1,6,1

#### 7. Extract time elapsed between dates

In [51]:
import datetime

today=datetime.datetime.today()

In [52]:
today

datetime.datetime(2026, 10, 15, 14, 48, 41, 587278)

In [53]:
today-date["date"]

0     2501 days 14:48:41.587278
1     2983 days 14:48:41.587278
2     2914 days 14:48:41.587278
3     2616 days 14:48:41.587278
4     2839 days 14:48:41.587278
                 ...
995   2929 days 14:48:41.587278
996   2870 days 14:48:41.587278
997   2718 days 14:48:41.587278
998   2783 days 14:48:41.587278
999   2557 days 14:48:41.587278
Name: date, Length: 1000, dtype: timedelta64[us]

In [54]:
(today-date["date"]).dt.days

0      2501
1      2983
2      2914
3      2616
4      2839
       ...
995    2929
996    2870
997    2718
998    2783
999    2557
Name: date, Length: 1000, dtype: int64

In [57]:
# Days Passed

np.round((today - date['date']) / np.timedelta64(1, 'D') / 30.44, 0)

0      82.0
1      98.0
2      96.0
3      86.0
4      93.0
       ...
995    96.0
996    94.0
997    89.0
998    91.0
999    84.0
Name: date, Length: 1000, dtype: float64

### Working with time

In [58]:
time

                    date                                                msg
0    2013-12-15 00:50:00                           ищу на сегодня мужика 37
1    2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2    2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3    2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4    2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше
..                   ...                                                ...
995  2012-03-16 00:50:00     ПАРЕНЬ СДЕЛАЕТ  МАССАЖ ЖЕНЩИНАМ -066-877-32-44
996  2014-01-23 23:14:00            сельский п 23 ищу девушку для отношений
997  2012-10-15 23:37:00  Д+Д ДЛЯ серьезных отношений. Мой номер 093-156...
998  2012-06-21 23:34:00  7 ДНЕПР М.34 ПОЗ.С Д/Ж ДЛЯ ВСТРЕЧ.Т.098 809 15 14
999  2014-06-19 23:25:00          Парень поласкает девушке...  т.0662035584

[1000 rows x 2 columns]

In [59]:
# Converting to datetime datatype

time['date'] = pd.to_datetime(time['date'])

In [60]:
time.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[us]
 1   msg     1000 non-null   str
dtypes: datetime64[us](1), str(1)
memory usage: 15.8 KB

In [61]:
time['hour'] = time['date'].dt.hour
time['min'] = time['date'].dt.minute
time['sec'] = time['date'].dt.second

time.head()

,date,msg,hour,min,sec
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0

#### Extract Time Part

In [62]:
time['time'] = time['date'].dt.time

time.head()

,date,msg,hour,min,sec,time
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0,00:50:00
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0,23:40:00
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0,00:21:00
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0,00:31:00
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0,23:11:00

#### Extract Time Diffrence

In [63]:
today-time["date"]

0     4687 days 13:58:41.587278
1     4551 days 15:08:41.587278
2     5037 days 14:27:41.587278
3     4339 days 14:17:41.587278
4     4736 days 15:37:41.587278
                 ...
995   5326 days 13:58:41.587278
996   4647 days 15:34:41.587278
997   5112 days 15:11:41.587278
998   5228 days 15:14:41.587278
999   4500 days 15:23:41.587278
Name: date, Length: 1000, dtype: timedelta64[us]

In [64]:
# in seconds

(today - time['date'])/np.timedelta64(1,'s')

0      4.050071e+08
1      3.932609e+08
2      4.352489e+08
3      3.749411e+08
4      4.092467e+08
           ...
995    4.602167e+08
996    4.015569e+08
997    4.417315e+08
998    4.517541e+08
999    3.888554e+08
Name: date, Length: 1000, dtype: float64

In [65]:
# in minutes

(today - time['date'])/np.timedelta64(1,'m')

0      6.750119e+06
1      6.554349e+06
2      7.254148e+06
3      6.249018e+06
4      6.820778e+06
           ...
995    7.670279e+06
996    6.692615e+06
997    7.362192e+06
998    7.529235e+06
999    6.480924e+06
Name: date, Length: 1000, dtype: float64

In [66]:
# in hours

(today - time['date'])/np.timedelta64(1,'h')

0      112501.978219
1      109239.144885
2      120902.461552
3      104150.294885
4      113679.628219
           ...
995    127837.978219
996    111543.578219
997    122703.194885
998    125487.244885
999    108015.394885
Name: date, Length: 1000, dtype: float64