In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('cars.csv')

In [3]:
df.sample(5)

           brand  km_driven    fuel                 owner  selling_price
327      Hyundai      80000  Petrol  Fourth & Above Owner         254999
1037        Tata      90000  Diesel          Second Owner         250000
5946        Ford      48000  Diesel          Second Owner         475000
3400   Chevrolet      15000  Petrol           First Owner         550000
1352  Volkswagen     120000  Diesel           Third Owner         260000

In [7]:
df['brand'].value_counts()

brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Land                6
Force               6
Isuzu               5
Kia                 4
Ambassador          4
MG                  3
Daewoo              3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

In [8]:
df['brand'].nunique()

32

In [9]:
df['fuel'].value_counts()

fuel
Diesel    4402
Petrol    3631
CNG         57
LPG         38
Name: count, dtype: int64

In [10]:
df['owner'].value_counts()

owner
First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5
Name: count, dtype: int64

## One Hot Encoding using Pandas

In [13]:
pd.get_dummies(df,columns=['fuel','owner'])

,brand,km_driven,selling_price,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_First Owner,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,False,True,False,False,True,False,False,False,False
1,Skoda,120000,370000,False,True,False,False,False,False,True,False,False
2,Honda,140000,158000,False,False,False,True,False,False,False,False,True
3,Hyundai,127000,225000,False,True,False,False,True,False,False,False,False
4,Maruti,120000,130000,False,False,False,True,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,False,True,True,False,False,False,False
8124,Hyundai,119000,135000,False,True,False,False,False,True,False,False,False
8125,Maruti,120000,382000,False,True,False,False,True,False,False,False,False
8126,Tata,25000,290000,False,True,False,False,True,False,False,False,False
8127,Tata,25000,290000,False,True,False,False,True,False,False,False,False

## K-1 Encoding (This is to solve Dummy Column Trap)

In [14]:
pd.get_dummies(df,columns=['fuel','owner'],drop_first=True)

,brand,km_driven,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,True,False,False,False,False,False,False
1,Skoda,120000,370000,True,False,False,False,True,False,False
2,Honda,140000,158000,False,False,True,False,False,False,True
3,Hyundai,127000,225000,True,False,False,False,False,False,False
4,Maruti,120000,130000,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,True,False,False,False,False
8124,Hyundai,119000,135000,True,False,False,True,False,False,False
8125,Maruti,120000,382000,True,False,False,False,False,False,False
8126,Tata,25000,290000,True,False,False,False,False,False,False
8127,Tata,25000,290000,True,False,False,False,False,False,False

### We only use pandas in one hot encoding for 'Data Analysis' purpose...we DO NOT use it for machine learning
##### Reason is :  pandas do not remember the details abt which column was at which position ...it could change and result in diffrent outputs maybe

## One Hot Encoding using Sklearn

In [15]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(df.iloc[:,0:4],
                                                df.iloc[:,-1],
                                                test_size = 0.2,
                                                random_state=0)

In [16]:
df.head(5)

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [19]:
from sklearn.preprocessing import OneHotEncoder

In [48]:
ohe = OneHotEncoder(drop='first',sparse_output=False,dtype=np.int32)

In [51]:
x_train_new = ohe.fit_transform(x_train[['fuel','owner']])

In [52]:
x_test_new = ohe.fit_transform(x_test[['fuel','owner']])

In [53]:
x_train_new.shape

(6502, 7)

In [54]:
x_train[["brand","km_driven"]].values

array([['Hyundai', 60000],
       ['Tata', 150000],
       ['Hyundai', 110000],
       ...,
       ['Hyundai', 90000],
       ['Volkswagen', 90000],
       ['Hyundai', 110000]], shape=(6502, 2), dtype=object)

In [55]:
np.hstack((x_train[["brand","km_driven"]].values,x_train_new))

array([['Hyundai', 60000, 0, ..., 0, 0, 0],
       ['Tata', 150000, 1, ..., 0, 0, 1],
       ['Hyundai', 110000, 1, ..., 1, 0, 0],
       ...,
       ['Hyundai', 90000, 0, ..., 1, 0, 0],
       ['Volkswagen', 90000, 1, ..., 0, 0, 0],
       ['Hyundai', 110000, 0, ..., 0, 0, 0]],
      shape=(6502, 9), dtype=object)

In [56]:
x_train_new

array([[0, 1, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 1],
       [1, 0, 0, ..., 1, 0, 0],
       ...,
       [0, 0, 1, ..., 1, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0]], shape=(6502, 7), dtype=int32)

In [57]:
np.hstack((x_train[["brand","km_driven"]].values,x_train_new)).shape

(6502, 9)

In [58]:
x_test_new

array([[1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       ...,
       [1, 0, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       [1, 0, 0, ..., 1, 0, 0]], shape=(1626, 7), dtype=int32)

In [65]:
df=pd.DataFrame(np.hstack((x_train[["brand","km_driven"]].values,x_train_new)))

In [66]:
df

               0       1  2  3  4  5  6  7  8
0        Hyundai   60000  0  1  0  0  0  0  0
1           Tata  150000  1  0  0  0  0  0  1
2        Hyundai  110000  1  0  0  0  1  0  0
3       Mahindra   28000  1  0  0  0  1  0  0
4         Maruti   15000  0  0  1  0  0  0  0
...          ...     ... .. .. .. .. .. .. ..
6497        Tata   70000  1  0  0  0  0  0  1
6498        Ford  100000  1  0  0  0  1  0  0
6499     Hyundai   90000  0  0  1  0  1  0  0
6500  Volkswagen   90000  1  0  0  0  0  0  0
6501     Hyundai  110000  0  0  1  0  0  0  0

[6502 rows x 9 columns]

## One Hot Encoding on Top categories

In [67]:
data=pd.read_csv("cars.csv")

In [68]:
data["brand"].value_counts()

brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Land                6
Force               6
Isuzu               5
Kia                 4
Ambassador          4
MG                  3
Daewoo              3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

In [69]:
counts=data["brand"].value_counts()

In [70]:
data["brand"].nunique()
threshold=100

In [71]:
repl=counts[counts<=threshold].index

In [75]:
pd.get_dummies(data["brand"].replace(repl,"uncommon"),dtype=int).sample(5)

,BMW,Chevrolet,Ford,Honda,Hyundai,Mahindra,Maruti,Renault,Skoda,Tata,Toyota,Volkswagen,uncommon
6847,0,0,0,0,0,1,0,0,0,0,0,0,0
2562,0,0,0,0,0,1,0,0,0,0,0,0,0
753,0,0,0,0,0,0,0,0,0,1,0,0,0
2811,0,0,0,0,1,0,0,0,0,0,0,0,0
4393,0,0,0,0,0,0,0,0,0,0,0,0,1